### ISSUE TITLE
Pleroma

### ISSUE THREAD

**Issue by MissPasture** [CuteAP/fediverse.express#6]
- [x] Write Ansible playbook
- [x] Allow users to choose which software to install
- [ ] Allow users to choose which instance size to use
- [x] Allow users to choose a frontend, where applicable
- [x] Change all references to "Misskey" to something more generic
- [x] Execute Pleroma playbook instead of Misskey playbook when requested

**Comment by MissPasture** [comment]
Implemented in 1f15dd0. Choosing an instance size will be a different issue
